# OPEN_JDK_VERSION=8-jre-alpine docker-compose -f docker-compose.build.yml build --no-cache
# docker-compose -f docker-compose.build.yml push

version: '3.5'
services:
  java-builder:
    image: tjmt/java:runtime
    build: 
      context: .
      dockerfile: Dockerfile      
      args:
        IMAGE_JAVA_VERSION: ${OPEN_JDK_VERSION} # VERSÃO DA IMAGEM DO JAVA RUNTIME
        TimeZone: "America/Cuiaba" #OPCIONAL: default = America/Cuiaba
        Language: "pt_BR" #OPCIONAL: default = pt_BR
        Unicode: "UTF-8" #OPCIONAL: default = UTF-8